let word=('Hello');
word=('Bye');
console.log(word);
let word2=("owu");
word2=('bobu')
console.log(word2);
let word3=('com');
word=('dom');
console.log(word3);
let word4=('ua');
word4=('pl');
console.log(word4);
let number1=1;
number1=0.5;
console.log(number1);
let number2=10;
number2=('5');
console.log(number2);
let number3=-999;
number3=999;
console.log(number3);
let number4=123;
number4=321;
console.log(number4);
let number5=3.14;
number5=-3.14;
console.log(number5);
let number6=2.7;
number=-2.7;
console.log(number6);
let number7=16;
number7=-16;
console.log(number7);
let firstName='Nazarii';
let middleName='Hnydyn';
let lastName='Lyubomyrovych';
let person=(firstName +' '+ middleName +' '+ lastName);
console.log(person);

let promt1='Nazarii';
let promt2='Lyubomyrovych';
let promt3=21;
let mainText=`Welcome ${promt1},${promt2}.You are ${promt3} years old`;
console.log(mainText);
let a = 100;
 console.log(typeof a);
 let b = '100';
 console.log(typeof b);
 let c = true;
 console.log(typeof c);
 console.log('5' !== '6');
 console.log(5 > 6);
 console.log(5 >= 6);
 console.log(5 > '6');
 console.log(10 == 10);
 console.log(10 === 10 );
console.log(10 > 10);
console.log(10 < 10);
console.log(10 !== 10);
 console.log(123 > 123);
 console.log(123 == 123);


